name: CI
on: [push]
jobs:
  test:
    strategy:
      matrix:
        runs-on: ["windows-latest"]

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v1
      - name: Install Scoop
        uses: MinoruSekine/setup-scoop@main
      - name: Install KDash
        shell: pwsh
        run: |
          scoop bucket add kdash-bucket https://github.com/kdash-rs/scoop-kdash
          scoop install kdash
          kdash -h
